language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    - touch database/database.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - pip install --user codecov
    - php artisan migrate --database=sqlite --force
    - php artisan key:generate
